name: My First GitHub Action

on:
  push:
    branches:
      - main

jobs:
  hello-job:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display information
        run: |
          echo "Repository Name: ${{ github.repository }}"
          echo "Branch Name: ${{ github.ref_name }}"
          echo "Current Date:"
          date
